// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjHgGqa26jir-JHCJOTdyorywOjyOra4U',
    appId: '1:778802136684:web:6e5b88eb690aff8c34fa49',
    messagingSenderId: '778802136684',
    projectId: 'flutterkomikapp',
    authDomain: 'flutterkomikapp.firebaseapp.com',
    storageBucket: 'flutterkomikapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8z81rU9q2wNFo8aMrzx6sNmc3twuTBBg',
    appId: '1:778802136684:android:9c3a32345cf1419b34fa49',
    messagingSenderId: '778802136684',
    projectId: 'flutterkomikapp',
    storageBucket: 'flutterkomikapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_4WVMRRawLuw29N11Gl5mBG-xeravOMA',
    appId: '1:778802136684:ios:885898122d4de0ef34fa49',
    messagingSenderId: '778802136684',
    projectId: 'flutterkomikapp',
    storageBucket: 'flutterkomikapp.appspot.com',
    iosBundleId: 'com.example.appKomikManga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_4WVMRRawLuw29N11Gl5mBG-xeravOMA',
    appId: '1:778802136684:ios:885898122d4de0ef34fa49',
    messagingSenderId: '778802136684',
    projectId: 'flutterkomikapp',
    storageBucket: 'flutterkomikapp.appspot.com',
    iosBundleId: 'com.example.appKomikManga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjHgGqa26jir-JHCJOTdyorywOjyOra4U',
    appId: '1:778802136684:web:e5d62a2d5daa76d534fa49',
    messagingSenderId: '778802136684',
    projectId: 'flutterkomikapp',
    authDomain: 'flutterkomikapp.firebaseapp.com',
    storageBucket: 'flutterkomikapp.appspot.com',
  );

}